import React from 'react'
import ReactDOM from 'react-dom'

// Since the index.html is generated by webpack it doesn't
// have a place to render React components by default so
// we have to create one and append it to the DOM.

const reactNode = document.createElement('div')
document.body.insertBefore(reactNode, document.body.firstChild)

const FirstComponent = () => (
  <h1>YO</h1>
)

ReactDOM.render(<FirstComponent />, reactNode)
